# code: language=ansible
---
- name: Update SpamAssassin setting
  ansible.builtin.blockinfile:
    path: "{{ spamassassin_config_dir }}/local.cf"
    block: "{{ spamassassin_cfg }}"
    marker: "# {mark} spamassassin role ANSIBLE MANAGED BLOCK"
    mode: "0644"
  notify: Restart spamassassin
