# code: language=ansible
---
- name: Restart spamassassin
  ansible.builtin.systemd:
    state: restarted
    name: spamd
- name: Reload spamassassin
  ansible.builtin.systemd:
    state: reloaded
    name: spamd
