# code: language=ansible
---
- name: Install repository dependency packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
# - name: Add apt signing key
#   ansible.builtin.get_url:
#     url: "{{ spamassassin_apt_key_url }}"
#     dest: "{{ spamassassin_apt_key_dest }}"
#     mode: "0644"
# - name: Add spamassassin repository
#   ansible.builtin.apt_repository:
#     filename: spamassassin
#     repo: deb [signed-by={{ spamassassin_apt_key_dest }}] https://packages.repository.com/debian {{ ansible_facts.distribution_release }} main
#     state: present
