# code: language=ansible
---
- name: Service SpamAssassin spam filtering daemon is active and enabled on system startup
  ansible.builtin.systemd:
    name: spamd
    state: started
    enabled: true
